name: Publish to Azure Function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: jjgnet          # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  SOLUTION_TO_BUILD:  './src/JosephGuadagnoNet.Broadcasting.sln'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Replace nlog.config
      run: yes | cp -i ./src/JosephGuadagno.Broadcasting.Functions/nlog.prod.config ./src/JosephGuadagno.Broadcasting.Functions/nlog.config
    - name: Replace host.json
      run: yes | cp -i ./src/JosephGuadagno.Broadcasting.Functions/host.prod.json ./src/JosephGuadagno.Broadcasting.Functions/host.json
    - name: Install dependencies
      run: dotnet restore ${{ env.SOLUTION_TO_BUILD }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION_TO_BUILD }} --configuration Release --no-restore --output ./output
    #- name: Test
    #  run: dotnet test ${{ env.SOLUTION_TO_BUILD }} --no-restore --verbosity normal
    - name: Run Azure Functions Action
      uses: Azure/functions-action@v1.4.0
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        # Enable build action from Kudu when the package is deployed onto the function app. This will temporarily change the SCM_DO_BUILD_DURING_DEPLOYMENT setting for this deployment. To bypass this and use the existing settings from your function app, please set this to an empty string ''. To enable remote build for your project, please set this and 'enable-oryx-build' both to 'true'. By default, GitHub Action respects the packages resolved in GitHub workflow, disabling the redundant build action from Kudu endpoint. (default: 'false').
        scm-do-build-during-deployment: false
        # Use Oryx Build from Kudu when the package is deployed onto the function app. (Linux functions only). This will temporarily change the ENABLE_ORYX_BUILD setting from this deployment. To bypass this and use the existing settings from your function app, please set this to an empty string ''. To enable remote build for your project, please set this and 'scm-do-build-during-deployment' both to 'true'. By default, GitHub Action respects the packages resolved in GitHub workflow, disabling the redundant build action from Kudu endpoint. (default: 'false').
        enable-oryx-build: false
