name: Publish to Azure Function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: jjgnet          # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  SOLUTION_TO_BUILD:  './src/JosephGuadagnoNet.Broadcasting.sln'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Replace host.json
      run: yes | cp -i ./src/JosephGuadagno.Broadcasting.Functions/host.prod.json ./src/JosephGuadagno.Broadcasting.Functions/host.json
    - name: Install dependencies
      run: dotnet restore ${{ env.SOLUTION_TO_BUILD }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION_TO_BUILD }} --configuration Release --no-restore --output ./output
    #- name: Test
    #  run: dotnet test ${{ env.SOLUTION_TO_BUILD }} --no-restore --verbosity normal
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
